---
title: "Day 4 Comp Session 1"
format: html
editor: visual
---

## Create Vectors

```{r}
rain <- c(3,5,10.1,6)
class(rain)
rain_scale <- 5 * rain
```

```{r}

```

## Create matricies

```{r}

my_values <- seq(from = 1, to = 10)
my_matrix <- matrix( data = my_values, nrow = 2, ncol = 5, byrow= TRUE)
my_matrix
```

```{r}
my_matrix2 <- matrix(data= my_values, nrow = 3, ncol = 4, byrow = TRUE)
my_matrix2
```

```{r}
matrixA <- matrix(data = seq(from = 2, to = 5, length = 10),
                  nrow = 2, ncol = 5,
                  byrow = TRUE)
matrixA
```

```{r}
my_matrix + matrixA
```

## Matrix Multiplication

```{r}
cats <- matrix( data = c(0,4,3,1), nrow = 2, ncol = 2, byrow= TRUE)
dogs <- matrix( data= c(6, -3, 0, 2), nrow = 2, ncol = 2, byrow = TRUE)

```

```{r}
dogs %*% cats
```

## Leslie Matrix Example

```{r}
insect_leslie <- matrix ( data = c(0,0,600,0.2,0,0,0,.08, 0), 
                          nrow = 3, 
                          ncol = 3,
                          byrow= TRUE)
insect_y0 <- c(12000, 700, 500)
```

### Find the population structure for each life stage at t = 1 year

```{r}
insect_y1 <- insect_leslie %*% insect_y0
```

The results of this mean that we expect there to be 300,000 eggs in the next cycle, 2400 larvae in the next cycle, and 56 adults in the next cycle.

### Find population structure at year 2 ( use insect_y1)

```{r}
insect_y2 <- insect_leslie %*% insect_y1
insect_y2
```
